### ISSUE TITLE
Submit this as a payload to the Bashbunny-payloads repo

### ISSUE THREAD

**Issue by sebkinne** [saintcrossbow/SmartFileExtract#1]
Hi @saintcrossbow -

I would love to see this payload submitted to [https://github.com/hak5/bashbunny-payloads](https://github.com/hak5/bashbunny-payloads). It seems like something many others would benefit from.

We would just ask that you do not include the .exe file, and allow users to download that themselves (to not clutter the repository with binary files).

**Comment by saintcrossbow** [comment]
Sebkinne:

Thanks for the good feedback. Once I get through the holidays I'll clean up the project a bit and then post. Have a great thanksgiving!

**Comment by sebkinne** [comment]
That's excellent news! I'm looking forward to it.

Have a great holiday!

**Comment by saintcrossbow** [comment]
Changes made:
a) Cleaned up project here to remove any unneeded files
b) Updated the documentation after better proof-reading and included examples
c) Updated default payload to include the one I always use 
d) Pull request submitted: https://github.com/hak5/bashbunny-payloads/pull/296
